export const ListaUNRC = [
  {
    matricula_carrera: "23105678-2",
    fecha_nacimiento: "1995-04-22",
    nombres: "CARLA",
    primer_apellido: "MARTÍNEZ",
    segundo_apellido: "LOZANO",
    curp: "MALC950422MMNZNX05",
    correo: "carla.martinez@example.com",
    modalidad: "Escolarizada",
    licenciatura: "Licenciatura en Administración",
    unidad_acedemica: "Unidad Central",
    nueva_sede: "Campus Sur",
    plan_estudio: "Plan 2022 - 2026",
    semestre: "3",
    grupo: "ADM-304-CSU",
  },
  {
    matricula_carrera: "22104187-1",
    fecha_nacimiento: "1980-10-08",
    nombres: "AQUILINO",
    primer_apellido: "PORTES",
    segundo_apellido: "TOLENTINO",
    curp: "POTA801008HHGRLQ05",
    correo: "aquilino.portes@gmail.com",
    modalidad: "A Distancia-Híbrida",
    licenciatura: "Licenciatura en Mercadotecnia y Ventas",
    unidad_acedemica: "A distancia",
    nueva_sede: "",
    plan_estudio: "Plan 2018 - 2020",
    semestre: "7",
    grupo: "DHLMV-704-GAM",
  },
];
